# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'CarCheck' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarCheck
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'JPush'
pod 'BMKLocationKit-NO-IDFA'
pod 'MMDrawerController', '~> 0.5.7'
pod 'ReactiveCocoa','~>2.1.8'
pod 'PPBadgeView'
end
